'use client'
import { useState } from 'react'
import { AgentPage, Field, TextInput, NumberInput, SelectInput, CheckboxGroup } from '@/components/agents/AgentShell'

const MEMO_TYPES = [{ value: 'post_meeting_recap', label: 'Post-Meeting Recap' }, { value: 'ic_memo', label: 'IC Memo' }, { value: 'suitability_memo', label: 'Suitability Memo' }, { value: 'client_followup_email', label: 'Customer Follow-up Email' }]
const AUDIENCES = [{ value: 'internal_ic', label: 'Internal IC' }, { value: 'rm_only', label: 'RM Only' }, { value: 'compliance', label: 'Compliance' }, { value: 'client', label: 'Customer' }]
const COMPLIANCE = [{ value: 'MAS', label: 'MAS (Singapore)' }, { value: 'SEBI', label: 'SEBI (India)' }, { value: 'FCA', label: 'FCA (UK)' }, { value: 'SEC', label: 'SEC (US)' }]
const SECTIONS = [{ value: 'decisions', label: 'Decisions' }, { value: 'action_items', label: 'Action Items' }, { value: 'risk_flags', label: 'Risk Flags' }, { value: 'next_steps', label: 'Next Steps' }]

export default function MemoMakerPage() {
  const [clientId, setClientId] = useState('CLI-883201')
  const [meetingId, setMeetingId] = useState('MTG-2026-05-12-001')
  const [memoType, setMemoType] = useState('post_meeting_recap')
  const [audience, setAudience] = useState('internal_ic')
  const [maxWords, setMaxWords] = useState('600')
  const [complianceRegion, setComplianceRegion] = useState('MAS')
  const [mustInclude, setMustInclude] = useState(['decisions', 'action_items', 'risk_flags', 'next_steps'])
  const [transcriptUri, setTranscriptUri] = useState('s3://rm-notes/mtg_20260512.txt')
  const [briefUri, setBriefUri] = useState('s3://rm-notes/BRF-MTG-2026-05-12-001.json')

  const buildPayload = () => {
    if (!clientId || !meetingId) return null
    return {
      agent: 'memo_maker', version: '1.0', rm_id: 'RM-04812',
      memo_type: memoType,
      subject: { client_id: clientId, meeting_id: meetingId },
      sources: [
        { type: 'meeting_transcript', uri: transcriptUri },
        { type: 'prior_brief', uri: briefUri },
      ].filter(s => s.uri),
      audience, format: 'markdown',
      must_include: mustInclude,
      max_words: Number(maxWords),
      compliance_region: complianceRegion,
    }
  }

  return (
    <AgentPage
      agentId="memo_maker" label="Memo Maker" icon="FileText"
      tagline="Post-meeting recap with decisions, action items & risk flags" color="#d97706" latency="~27s"
      buildPayload={buildPayload}
      form={
        <>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
            <Field label="Customer ID"><TextInput value={clientId} onChange={setClientId} placeholder="CLI-883201" /></Field>
            <Field label="Meeting ID"><TextInput value={meetingId} onChange={setMeetingId} placeholder="MTG-2026-05-12-001" /></Field>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
            <Field label="Memo Type"><SelectInput value={memoType} onChange={setMemoType} options={MEMO_TYPES} /></Field>
            <Field label="Audience"><SelectInput value={audience} onChange={setAudience} options={AUDIENCES} /></Field>
          </div>
          <Field label="Meeting Transcript (S3 URI)" hint="Transcript of the meeting"><TextInput value={transcriptUri} onChange={setTranscriptUri} placeholder="s3://rm-notes/..." /></Field>
          <Field label="Prior Brief (S3 URI)" hint="Pre-meeting brief generated by Meeting Preparer"><TextInput value={briefUri} onChange={setBriefUri} placeholder="s3://rm-notes/..." /></Field>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
            <Field label="Max Words"><NumberInput value={maxWords} onChange={setMaxWords} min={100} max={2000} /></Field>
            <Field label="Compliance Region"><SelectInput value={complianceRegion} onChange={setComplianceRegion} options={COMPLIANCE} /></Field>
          </div>
          <Field label="Must Include Sections"><CheckboxGroup value={mustInclude} onChange={setMustInclude} options={SECTIONS} /></Field>
        </>
      }
    />
  )
}
